spring.application.name=EasyTraza
spring.datasource.url=jdbc:mysql://localhost:3306/easytraza?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Permitir subir fotos del m\u00f3vil (hasta 20MB)
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

gemini.api.key=AIzaSyBWgksE3LM6_hbZjoHbUczzHBdR8dEr6_k

# recuperar contrase\u00f1a

# Configuraci\u00f3n de Spring Mail para Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=easytraza@gmail.com
spring.mail.password=nomxktzfqhirraew
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Caducidad de la sesi\u00f3n por inactividad (30 minutos)
server.servlet.session.timeout=30m